version: "2.4"

volumes:
  database:
    name: tcrs-db
  blockchain:
    name: tcrs-data
  
services:

  indexer:
    container_name: tcrs-indexer
    image: blockcore/indexer-crs:0.2.27
    environment:
      VIRTUAL_HOST: tcrs.indexer.blockcore.net
      VIRTUAL_PORT: 9910
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: tcrs.indexer.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
      ASPNETCORE_URLS: https://*:9910
      Logging__LogLevel__Default: Debug
    command: ["--chain=TCRS"]
    restart: unless-stopped
    depends_on:
        - mongo
        - chain

  chain:
    container_name: tcrs-chain
    image: blockcore/node-crs:1.1.36
    command: ["-server=1", "-iprangefiltering=0", "-rpcallowip=192.168.0.0/8", "-rpcallowip=172.0.0.0/8", "-rpcbind=0.0.0.0", "-apiuri=http://0.0.0.0:37223", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword", "-testnet"]
    restart: unless-stopped
    stop_grace_period: 15m
    volumes:
      - blockchain:/root/.blockcore
    ports:
      - 26179:26179 # Make this a public node.

  mongo:
    container_name: tcrs-mongo
    image: mongo:5.0.5
    mem_limit: 15000m
    restart: unless-stopped
    stop_grace_period: 5m
    volumes:
      - database:/data/db
      - database:/data/configdb

