version: "2.4"

volumes:
  database:
    name: tcrs-db
  blockchain:
    name: tcrs-data
  
services:

  indexer:
    container_name: tcrs-indexer
    image: blockcore/indexer-crs:0.2.35
    mem_limit: 1024m
    cpus: 1.00
    environment:
      VIRTUAL_HOST: tcrs.indexer.blockcore.net
      VIRTUAL_PORT: 9910
      VIRTUAL_PROTO: http
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: tcrs.indexer.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
      ASPNETCORE_URLS: https://+:9910
      Logging__LogLevel__Default: Debug
    command: ["--chain=TCRS"]
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
      chain:
        condition: service_healthy
    networks:
      - tcrsnetwork
      - proxy

  chain:
    container_name: tcrs-chain
    image: blockcore/node-crs:1.1.47
    mem_limit: 6144m
    cpus: 1.00
    healthcheck:
      test: curl --fail http://localhost:38223/api/Node/status || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    command: ["-server=1", "-iprangefiltering=0", "-rpcallowip=10.202.0.0/8", "-rpcallowip=10.201.0.0/8", "-rpcallowip=192.168.0.0/8", "-rpcallowip=172.0.0.0/8", "-rpcbind=0.0.0.0", "-apiuri=http://0.0.0.0:38223", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword", "-testnet"]
    restart: unless-stopped
    stop_grace_period: 15m
    volumes:
      - blockchain:/root/.stratisnode
    ports:
      - 26179:26179 # Make this a public node.
    networks:
      - tcrsnetwork

  mongo:
    container_name: tcrs-mongo
    image: mongo:5.0.5
    mem_limit: 2048m
    cpus: 1.00
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    stop_grace_period: 5m
    volumes:
      - database:/data/db
      - database:/data/configdb
    networks:
      - tcrsnetwork
networks:
  tcrsnetwork:
    external: false
    name: tcrsnetwork
  proxy:
    external: true
    name: proxy